name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build, publish then deploy
    runs-on: ubuntu-latest

    steps:
      #- uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            registry.knatofs.se/yaml-converter
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short
      - uses: docker/login-action@v2
        with:
          registry: registry.knatofs.se
          username: mats
          password: ${{ secrets.DCR_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  publish:
    name: Apply changes in kubernetes
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Deploy scripted application
        uses: matst80/slask-action@main
        with:
          k8sConfig: ${{ secrets.K8S_CONFIG }}
          scriptPath: deploy.js
