name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build, publish then deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: registry.knatofs.se
          username: mats
          password: ${{ secrets.DCR_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: true
          tags: "registry.knatofs.se/yaml-converter:${{github.sha}}"
      - name: Deploy scripted application
        uses: matst80/slask-action@v1
        with:
          k8sConfig: ${{ secrets.K8S_CONFIG }}
          scriptPath: deploy.js
